[package]
name = "hadocrx"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ffi-convert = "0.6.2"
fuzzy-matcher = "0.3.7"
json = "0.12.4"
rusqlite = { version = "0.37.0", features = ["bundled"] }
rusqlite_migration = "2.3.0"
