on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Setup linux environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Build linux app
        run: flutter build linux
      - name: Create AppDir
        run: |
          mkdir -p AppDir/bin AppDir/lib
          find build/linux/x64/release/bundle -maxdepth 1 -type f -executable | xargs ldd | grep "=>" | grep -v "not found" | grep -oP '(?<= => )[^ ]+' | xargs -I{} cp {} AppDir/lib/
          find build/linux/x64/release/bundle -maxdepth 1 -type f -executable | xargs -I{} cp {} AppDir/bin/
          cp -r build/linux/x64/release/bundle/data AppDir/bin/
          cat > AppDir/AppRun <<EOF
          #! /bin/sh

          set -e
          this_dir="\$(readlink -f \"\$(dirname \"\$0\")\")"
          export LD_LIBRARY_PATH="\$this_dir/lib:\$LD_LIBRARY_PATH"
          export PATH="\$this_dir/bin:\$PATH"
          exec "\$this_dir/bin/hadocrx" "\$@"
          EOF
          cat AppDir/AppRun
      - name: Build apk
        run: flutter build apk --release --split-per-abi
      - name: Package artifacts
        run: |
          mkdir artifacts
          cp -r build/app/outputs/flutter-apk artifacts/
          cp -r build/linux/x64/release/bundle artifacts/
          mv artifacts/bundle artifacts/linux
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: artifacts