on: workflow_dispatch

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build ipa
        run: flutter build ipa --release --no-codesign
      - name: Build apk
        run: flutter build apk --release --split-per-abi
      - name: Compress artifacts
        run: tar czvf build.tar.gz --transform='s,^,build/,' build/app/outputs/flutter-apk build/ios/iphoneos
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.gz